# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e555e94ebc6523ad6ae06ec9d7633df6266227c09852112f4d55dd592f5c3b4c4c8daadd783d606b12c7e24de0a0a37729ce6616683d68d94e7f006198629a29

test:
  secret_key_base: ca1511d3c22addf4cfa2a151b675ce206c2dfd3bc649ef5efd3586718defee30f8607ff332eeef026cc73fa14d8ea573eeb02de00893fc6b0f57236cffe4f5a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
